### ISSUE TITLE
Expected a single document in the stream

### ISSUE THREAD

**Issue by theflow** [replicatedhq/studio#31]
Hi,

I'm getting this error following the dev environment docs for docker-swarm https://help.replicated.com/docs/swarm/getting-started/development-environment/

```
[getAppUpgrades:80d92d1c] <- POST /v1/app/c198f77f184445f04c59cad6dce8df3b/upgrades
[getAppUpgrades:80d92d1c] <- {"CurrentVersion":3,"LastKnownVersion":3,"InstallationId":"37c2cea18e1c4bf345205eb2d216110b","FullUpdate":true}
[getAppUpgrades:80d92d1c] !! 500 YAMLException: expected a single document in the stream, but found more
    at load (/usr/local/lib/node_modules/replicated-studio/node_modules/js-yaml/lib/js-yaml/loader.js:1577:9)
    at Object.safeLoad (/usr/local/lib/node_modules/replicated-studio/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at Object.fillOutYaml (/usr/local/lib/node_modules/replicated-studio/src/replicated/release.ts:94:20)
    at _.forEach (/usr/local/lib/node_modules/replicated-studio/src/handlers/getAppUpgrades.ts:34:26)
    at arrayEach (/usr/local/lib/node_modules/replicated-studio/node_modules/lodash/lodash.js:508:11)
    at Function.forEach (/usr/local/lib/node_modules/replicated-studio/node_modules/lodash/lodash.js:9334:14)
    at /usr/local/lib/node_modules/replicated-studio/src/handlers/getAppUpgrades.ts:31:5
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/replicated-studio/dist/handlers/getAppUpgrades.js:7:71
    at new Promise (<anonymous>)

```

Is that related to #30 and currently doesn't work with docker-swarm?

**Comment by emosbaugh** [comment]
This is solved by #30 . Based on the stack trace the release being used was prior to that commit.
