### ISSUE TITLE
Yml deemed valid by replicated console causes errors in studio

### ISSUE THREAD

**Issue by eddiewebb** [replicatedhq/studio#35]
When attempting to get studio to "check for latest" the logs throw an error for the same yaml that it loaded from our server and installed successfully.  No changes can be introduced.  

```
[getAppUpgrades:db774d72] <- {"CurrentVersion":6162,"LastKnownVersion":6162,"InstallationId":"2d5d921e7cc4487954baa98a761a0d9f","FullUpdate":true}
[getAppUpgrades:db774d72] !! 500 YAMLException: end of the stream or a document separator is expected at line 15, column 7:
          source: ""
          ^
    at generateError (/usr/local/lib/node_modules/replicated-studio/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/usr/local/lib/node_modules/replicated-studio/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readDocument (/usr/local/lib/node_modules/replicated-studio/node_modules/js-yaml/lib/js-yaml/loader.js:1512:5)
    at loadDocuments (/usr/local/lib/node_modules/replicated-studio/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/usr/local/lib/node_modules/replicated-studio/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/usr/local/lib/node_modules/replicated-studio/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at _.map (/usr/local/lib/node_modules/replicated-studio/src/replicated/release.ts:117:24)
    at arrayMap (/usr/local/lib/node_modules/replicated-studio/node_modules/lodash/lodash.js:631:23)
    at Function.map (/usr/local/lib/node_modules/replicated-studio/node_modules/lodash/lodash.js:9546:14)
    at fillOutYamlString (/usr/local/lib/node_modules/replicated-studio/src/replicated/release.ts:110:12)
```

It should be noted that line 15 does not contain `source`

**Comment by emosbaugh** [comment]
hi @eddiewebb is it possible to share yaml so that we can reproduce this? thanks
